# Nom de votre projet
# (utilisez un seul mot, exemple: 'monprojet')
PROJECTNAME= libTest

# Fichiers sources
# (Listez tous les fichiers a compiler, ex: 'tp1.c, tp2.cpp'):
# Utilisez le suffixe .cpp pour les fichiers C++
PRJSRC= defaultISR.cpp engine.cpp led.cpp lib.cpp pinPosition.cpp timer.cpp uart.cpp ram.cpp

SUFF = a

#compilateur utilise
CCR=avr-ar rcs

LDFLAGS=

INCL =

LIBS =

EXT =

-include ../Makefile_common.txt
